/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package scheduler;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Set;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class HolTaskDialog extends javax.swing.JDialog {
    private String Source;
    private String yesNoInd;
    private String reverseYesNoInd;
    private String seperator = Preferences.SEPERATOR;
    // TODO Sort out initialise Button - what it initialises flex2DArray or serialised object also.
    /**
     * Creates new form HolTaskDialog
     * The convention as to what the contents of holidays and assignments mean is
     * set in this module. In both "Y" means available. Thus for holidays we will
     * display in this dialog entries where the value is "N" since a holiday means 
     * unavailable for duty. On the other hand the assignments will show entries
     * with a "Y" in this dialog since the the individual is available for that 
     * duty. Initialisations will also differ. Holidays will be initiated with
     * "Y" (default is available), assignments with "N" (Default is unavailable).
     */
    public HolTaskDialog(java.awt.Frame parent, boolean modal,String source) {
        super(parent, modal);
        initComponents();
        // Application specific initialisation
        this.setTitle(source); //Title
        // Get people, dates and tasks allowed master data
        Source = source;
        for (String p : (ArrayList<String>) Preferences.retrieve(Preferences.PEOPLE_FILE)) peopleComboBox.addItem(p);
        String objectFile;
        if (source.equals("Holidays")) {
            yesNoInd = "N"; //Meaning chosen holidays are unavailable to schedule
            reverseYesNoInd = "Y";
        }
        else if (source.equals("Assignments")) {
            yesNoInd = "Y"; //Meaning chosen assignments are available to schedule
            reverseYesNoInd = "N";
        }
        // Display people, dates and tasks allowed master data
        DefaultListModel allowedLM = new DefaultListModel();
        allowedList.setModel(allowedLM);
        flex2DArray taskDates = Preferences.retrieveFlex2DArray(Preferences.TASK_DATE_FILE);
        if (source.equals("Holidays")){
            for (String date : taskDates.getColKeys()) allowedLM.addElement(date);
        }
        else {
            for (String task : taskDates.getRowKeys()) allowedLM.addElement(task);
        }
        //If assignments of holidays/tasks already made, show those
        if (source.equals("Holidays")) objectFile = Preferences.HOLIDAYS_FILE;
        else if (source.equals("Assignments")) objectFile = Preferences.ASSIGNMENTS_FILE;
        else objectFile = Preferences.HOLIDAYS_FILE;
        peopleComboBox.setSelectedIndex(0);
        DefaultListModel chosenLM = new DefaultListModel();
        chosenList.setModel(chosenLM);
        flex2DArray f = (flex2DArray) Preferences.retrieveFlex2DArray(objectFile);
        try{
            Set<String> s = f.getColKeysForRow((String)peopleComboBox.getSelectedItem(),yesNoInd);
            for (String p : s) chosenLM.addElement(p);
        }
        catch (NullPointerException e){
            // for (String line : f.print(seperator)) System.out.println();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        allowedLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        allowedList = new javax.swing.JList();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        chosenList = new javax.swing.JList();
        chosenLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        peopleComboBox = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        initialiseButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Holidays and Task Assignments");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Chooser"));

        allowedLabel.setText("Allowed");

        allowedList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        allowedList.setVisibleRowCount(20);
        jScrollPane1.setViewportView(allowedList);

        addButton.setText(">");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        removeButton.setText("<");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        closeButton.setForeground(new java.awt.Color(255, 51, 51));
        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(chosenList);

        chosenLabel.setText("Chosen");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allowedLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addButton)
                            .addComponent(removeButton))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chosenLabel)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allowedLabel)
                    .addComponent(chosenLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(18, 18, 18)
                        .addComponent(closeButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Person"));

        peopleComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peopleComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(peopleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(peopleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        initialiseButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        initialiseButton.setText("Initialise");
        initialiseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initialiseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(initialiseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(initialiseButton, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initialiseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initialiseButtonActionPerformed
        
        if (JOptionPane.showConfirmDialog(null, "Are you sure?","Confirm", JOptionPane.YES_NO_OPTION) ==
                JOptionPane.OK_OPTION) {
            flex2DArray fl2D;
            fl2D = initialise(Source);
            File f;
            if (Source.equals("Holidays")) f = new File(Preferences.HOLIDAYS_FILE);
            else if (Source.equals("Assignments")) f = new File(Preferences.ASSIGNMENTS_FILE);
            else {f = new File(Preferences.HOLIDAYS_FILE);}
            ObjectOutputStream oos;
            try {
                oos = new ObjectOutputStream(new FileOutputStream(f));
                oos.writeObject(fl2D);
                oos.close();
            }
            catch (IOException e) {
                System.out.println("Unable to create serialised object");
            }
            DefaultListModel DLM = new DefaultListModel();
            chosenList.setModel(DLM);
            DLM.clear();
        }
    }//GEN-LAST:event_initialiseButtonActionPerformed

    private void peopleComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peopleComboBoxActionPerformed
        //If assignments of holidays already made, show those
        String objectFile;
        if (Source.equals("Holidays")) objectFile = Preferences.HOLIDAYS_FILE;
        else if (Source.equals("Assignments")) objectFile = Preferences.ASSIGNMENTS_FILE;
        else objectFile = Preferences.HOLIDAYS_FILE;
        DefaultListModel chosenLM = new DefaultListModel();
        chosenList.setModel(chosenLM);
        flex2DArray f = (flex2DArray) Preferences.retrieveFlex2DArray(objectFile);
        try{
            Set<String> s = f.getColKeysForRow((String)peopleComboBox.getSelectedItem(),yesNoInd);
            for (String p : s) chosenLM.addElement(p);
        }
        catch (NullPointerException e){
            // for (String line : f.print(seperator)) System.out.println();
        }
    }//GEN-LAST:event_peopleComboBoxActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        Object[] L = chosenList.getSelectedValues();
        DefaultListModel LM = (DefaultListModel) chosenList.getModel();
        for (Object O : L) {
            LM.removeElement(O);
        }
        String rowKey = (String) peopleComboBox.getSelectedItem();
        ArrayList<String> selections = new ArrayList();
        for (int i = 0; i < chosenList.getModel().getSize(); i++) {
            selections.add((String) chosenList.getModel().getElementAt(i));
        }
        Preferences.updateRowInFlex2DArray(Source, rowKey, selections, yesNoInd, reverseYesNoInd);
        Preferences.enforceScheduleConsistency();
    }//GEN-LAST:event_removeButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        Object[] L = allowedList.getSelectedValues();
        DefaultListModel LM = (DefaultListModel) chosenList.getModel();
        for (Object O : L) LM.addElement(O);
        String rowKey = (String) peopleComboBox.getSelectedItem();
        ArrayList<String> selections = new ArrayList();
        for (int i = 0; i < chosenList.getModel().getSize(); i++) {
            selections.add((String) chosenList.getModel().getElementAt(i));
        }
        
        Preferences.updateRowInFlex2DArray(Source, rowKey, selections, yesNoInd, reverseYesNoInd);
        Preferences.enforceScheduleConsistency();
    }//GEN-LAST:event_addButtonActionPerformed
    
    private flex2DArray initialise(String src){
        flex2DArray fArray = new flex2DArray();
        flex2DArray choices = new flex2DArray();
        if (src.equals("Holidays")) {
            choices = Preferences.retrieveFlex2DArray(Preferences.HOLIDAYS_FILE);
        }
        else if (src.equals("Assignments")) {
            choices = Preferences.retrieveFlex2DArray(Preferences.ASSIGNMENTS_FILE);
        }
        for (String r :choices.getRowKeys()){
            for (String c : choices.getColKeys()) 
                if (src.equals("Holidays")){fArray.add(r,c,"Y");} // Default available
                else if (src.equals("Assignments")) {fArray.add(r,c,"N");} // Default not available
        }
        return fArray;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel allowedLabel;
    private javax.swing.JList allowedList;
    private javax.swing.JLabel chosenLabel;
    private javax.swing.JList chosenList;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton initialiseButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox peopleComboBox;
    private javax.swing.JButton removeButton;
    // End of variables declaration//GEN-END:variables
}
